version: '3' # composeファイルのバーション指定
services:
  app: # service名
    build:
      context: ./
      dockerfile: ./go_web/Dockerfile
    tty: true # コンテナの起動永続化
    volumes:
      - go-app_data:/go/src # マウントディレクトリ指定
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    build: ./go_mysql
    container_name: go_mysql
    ports:
      - 3307:3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: go_database
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    networks: 
      - go_network
    volumes:
      - go-db_data:/var/lib/mysql

volumes:
  go-db_data: {}
  go-app_data: {}
networks:
  go_network:
    driver: bridge